# Generated by Django 6.0.6 on 2026-06-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_quote_to_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sage',
            field=models.BooleanField(default=False),
        ),
    ]
