# Generated by Django 6.0.6 on 2026-06-15 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_sage_to_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='last_reply_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
