# Generated by Django 6.0.6 on 2026-06-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_tagline_badge_into_main_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='FaceChan', help_text='Displayed in the header and browser tab.', max_length=100)),
                ('site_tagline', models.CharField(blank=True, default='Anonymous-first community platform', help_text='Short tagline shown beneath the site name.', max_length=200)),
                ('max_boards', models.PositiveIntegerField(default=50, help_text='Maximum number of boards allowed on this instance.')),
                ('max_threads_per_board', models.PositiveIntegerField(default=200, help_text='Once reached, the oldest non-pinned thread is pruned when a new one is posted.')),
                ('max_threads_per_user_per_day', models.PositiveIntegerField(default=10, help_text='Rate limit — threads a single user can create per day. 0 = unlimited.')),
                ('max_posts_per_thread', models.PositiveIntegerField(default=500, help_text='Thread locks automatically when this many replies are reached.')),
                ('max_post_length', models.PositiveIntegerField(default=5000, help_text='Maximum character length for a post body.')),
                ('max_posts_per_user_per_day', models.PositiveIntegerField(default=100, help_text='Rate limit — posts a single user can make per day. 0 = unlimited.')),
                ('max_communities', models.PositiveIntegerField(default=100, help_text='Maximum number of communities allowed on this instance.')),
                ('max_communities_per_user', models.PositiveIntegerField(default=5, help_text='Maximum number of communities a single user can create.')),
                ('allow_image_uploads', models.BooleanField(default=True, help_text='Allow users to attach images to threads and posts.')),
                ('max_image_size_mb', models.PositiveIntegerField(default=8, help_text='Maximum image upload size in megabytes.')),
                ('registration_open', models.BooleanField(default=True, help_text='Allow new user registrations. Disable to make the instance invite-only.')),
                ('require_email', models.BooleanField(default=False, help_text='Require an email address at registration.')),
                ('enable_nsfw_boards', models.BooleanField(default=True, help_text='Allow boards to be marked NSFW.')),
                ('allow_anonymous_posts', models.BooleanField(default=False, help_text='Allow posting without being logged in (future feature).')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
