# Generated by Django 6.0.6 on 2026-06-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='block_nsfw_without_age_gate',
            field=models.BooleanField(default=True, help_text='Hide NSFW boards behind the age gate. Disable only where your jurisdiction does not require age-gating of adult content.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_content_reporting',
            field=models.BooleanField(default=True, help_text='Show a "report" control on threads and posts that routes to the moderation queue. Strongly recommended in all jurisdictions; required-in-effect under the UK OSA and EU DSA.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='jurisdiction_mode',
            field=models.CharField(choices=[('uk', 'United Kingdom (Online Safety Act)'), ('eu', 'European Union (Digital Services Act)'), ('us', 'United States (Section 230 host)'), ('other', 'Other / operator-defined')], default='uk', help_text="Operator's legal jurisdiction. Informational — sets sensible defaults and is surfaced in transparency reporting.", max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='minimum_age',
            field=models.PositiveIntegerField(default=18, help_text='Minimum age (years) a user must confirm at registration when age confirmation is enabled.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='moderation_contact',
            field=models.EmailField(blank=True, help_text='Public contact address for legal / moderation enquiries and content reports. Recommended for OSA/DSA operators.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='publish_transparency_info',
            field=models.BooleanField(default=True, help_text='Expose a public transparency page (instance jurisdiction, moderation contact, reporting routes). Good-faith disclosure.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_age_confirmation',
            field=models.BooleanField(default=True, help_text='Require users to confirm they meet the minimum age at registration. A jurisdictional control — UK/EU operators will generally need this; operators elsewhere may not.'),
        ),
    ]
