# Generated by Django 6.0.6 on 2026-06-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_compliance_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='max_posts_per_user_per_day',
            field=models.PositiveIntegerField(default=100, help_text='Rate limit — posts a single user can make per rolling 24 hours (not a calendar-day reset; the window slides with the clock). 0 = unlimited.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='max_threads_per_user_per_day',
            field=models.PositiveIntegerField(default=10, help_text='Rate limit — threads a single user can create per rolling 24 hours (not a calendar-day reset; the window slides with the clock). 0 = unlimited.'),
        ),
    ]
