# Generated by Django 6.0.6 on 2026-06-17 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_clarify_rolling_24h_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam or advertising'), ('harassment', 'Harassment or bullying'), ('illegal', 'Illegal content'), ('csam', 'Child sexual abuse material'), ('violence', 'Violence or graphic content'), ('hate', 'Hate speech'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Optional extra context from the reporter.', max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.post')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.thread')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', True), ('thread__isnull', False)), models.Q(('post__isnull', False), ('thread__isnull', True)), _connector='OR'), name='report_exactly_one_target')],
            },
        ),
    ]
