# Generated by Django 6.0.6 on 2026-06-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_report_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tier', models.PositiveSmallIntegerField(default=0, help_text='Higher = more capable. Used for ordering/display only — actual power comes from the capability flags below.')),
                ('is_admin_tier', models.BooleanField(default=False, help_text='Unscoped (every board/community) and can manage roles & role/board assignments. There should usually be very few roles with this set.')),
                ('can_hide', models.BooleanField(default=False, help_text='Hide threads/posts (reversible).')),
                ('can_resolve_reports', models.BooleanField(default=False, help_text='Mark reports reviewing/actioned/dismissed.')),
                ('can_delete', models.BooleanField(default=False, help_text='Permanently delete threads/posts.')),
                ('can_lock_threads', models.BooleanField(default=False)),
                ('can_suspend', models.BooleanField(default=False, help_text='Issue timed suspensions.')),
                ('can_ban', models.BooleanField(default=False, help_text='Issue permanent bans.')),
                ('can_manage_roles', models.BooleanField(default=False, help_text="Assign/change other users' roles and board assignments. Should normally only be set alongside is_admin_tier.")),
            ],
            options={
                'ordering': ['-tier'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='board_assignments',
            field=models.ManyToManyField(blank=True, related_name='staff_assignments', to='core.board'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.role'),
        ),
    ]
