# Generated by Django 6.0.6 on 2026-06-17 15:08
# Hand-edited: added a data migration step so any Role row that already
# had can_delete=True carries that over to can_quarantine rather than
# silently losing the value when the old field is dropped. Matters if
# this lands after feature/roles-and-sanctions is already merged and in
# use with real role data assigned — harmless no-op on a fresh database.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_can_delete_to_can_quarantine(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    Role.objects.filter(can_delete=True).update(can_quarantine=True)


def reverse_copy(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    Role.objects.filter(can_quarantine=True).update(can_delete=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_content_hiding'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_quarantined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='quarantine_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='quarantined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='quarantined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='can_purge',
            field=models.BooleanField(default=False, help_text='Permanently delete quarantined content. IRREVERSIBLE. Enforced as admin-tier-only in code regardless of this flag — see permissions.py can_purge_content(). The flag still exists for visibility/audit in the admin, not because a non-admin role can ever actually be granted it.'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_quarantine',
            field=models.BooleanField(default=False, help_text='Remove content from ALL visibility, including its own author — stays in the database pending an admin decision to restore or purge. Reversible. Intended for board-admin tier and above: content that may be illegal in some jurisdictions, or that law enforcement might need, gets held rather than destroyed by a single non-admin action. See COMPLIANCE.md for the legal caveat on retention — this is architecture, not legal advice.'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_quarantined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='quarantine_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='thread',
            name='quarantined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='quarantined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_hide',
            field=models.BooleanField(default=False, help_text='Hide threads/posts (reversible, visible to author/staff).'),
        ),
        migrations.RunPython(copy_can_delete_to_can_quarantine, reverse_copy),
        migrations.RemoveField(
            model_name='role',
            name='can_delete',
        ),
    ]
