# Generated by Django 6.0.6 on 2026-06-17 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_quarantine_and_purge'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='report_exactly_one_target',
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.post'),
        ),
        migrations.AlterField(
            model_name='report',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.thread'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', True), ('thread__isnull', False)), models.Q(('post__isnull', False), ('thread__isnull', True)), models.Q(('post__isnull', True), ('thread__isnull', True)), _connector='OR'), name='report_at_most_one_target'),
        ),
    ]
