# Generated by Django 6.0.6 on 2026-06-18 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_report_snapshot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_username_change_audit',
            field=models.BooleanField(default=True, help_text='Log every username change (old name, new name, when) to UsernameChangeLog. Independent of the cooldown below — turning this off stops new log entries but does not affect whether changes are still rate-limited.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='username_change_cooldown_days',
            field=models.PositiveIntegerField(default=14, help_text='Minimum days a user must wait between username changes. 0 = no cooldown. Enforced via User.username_last_changed_at, which is tracked regardless of the audit-log toggle above.'),
        ),
        migrations.AddField(
            model_name='user',
            name='username_last_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UsernameChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_username', models.CharField(max_length=150)),
                ('new_username', models.CharField(max_length=150)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='username_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
