# Generated by Django 6.0.6 on 2026-06-21 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_word_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='allow_videos',
            field=models.BooleanField(default=True, help_text='Allow users to attach short video clips (MP4/WebM) to threads and posts on this board.'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_duration',
            field=models.FloatField(blank=True, help_text='Duration of the attached video in seconds.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_pdq_hash',
            field=models.CharField(blank=True, editable=False, help_text='perceptual hash (pHash) of the video first frame. Used for CSAM hash-matching. Null if no video attached or if hashing failed.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_video_thumbs/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_video_uploads',
            field=models.BooleanField(default=True, help_text='Allow users to attach short video clips (MP4/WebM) to threads and posts. Requires FFmpeg to be installed on the server.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_video_duration_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Maximum video duration in seconds (default 300 = 5 minutes). 0 = no duration limit (not recommended).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_video_size_mb',
            field=models.PositiveIntegerField(default=50, help_text='Maximum video upload size in megabytes.'),
        ),
        migrations.AddField(
            model_name='thread',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='thread_videos/'),
        ),
        migrations.AddField(
            model_name='thread',
            name='video_duration',
            field=models.FloatField(blank=True, help_text='Duration of the attached video in seconds.', null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='video_pdq_hash',
            field=models.CharField(blank=True, editable=False, help_text='perceptual hash (pHash) of the video first frame. Used for CSAM hash-matching. Null if no video attached or if hashing failed.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thread_video_thumbs/'),
        ),
        migrations.AlterField(
            model_name='activitytier',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in admin. Lower numbers appear first. Does not affect tier calculation — that always uses min_posts.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_pdq_hash',
            field=models.CharField(blank=True, editable=False, help_text='perceptual hash (pHash) of the post image. Used for CSAM hash-matching. Null if no image attached or if hashing failed.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the poster at submission time. Admin-only. Raw address — handle as personal data per your jurisdiction.', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbs/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bump_lock_percent',
            field=models.PositiveIntegerField(default=75, help_text='Thread stops bumping to the top once reply count reaches this percentage of max_posts_per_thread. E.g. 75 means a 500-post thread bump-locks at 375 replies. Set to 0 to disable bump locking (threads bump until locked). Maximum 95 — values above this are clamped in code.', validators=[django.core.validators.MaxValueValidator(95)]),
        ),
        migrations.AlterField(
            model_name='thread',
            name='image_pdq_hash',
            field=models.CharField(blank=True, editable=False, help_text='perceptual hash (pHash) of the thread image. Used for CSAM hash-matching. Null if no image attached or if hashing failed.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='poster_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the poster at submission time. Admin-only. Raw address — handle as personal data per your jurisdiction.', null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thread_thumbs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_pdq_hash',
            field=models.CharField(blank=True, editable=False, help_text='perceptual hash (pHash) of the avatar image. Used for CSAM hash-matching. Null until an avatar is uploaded or if hashing failed.', max_length=64, null=True),
        ),
    ]
