# Generated by Django 6.0.6 on 2026-06-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_video_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='allow_video_sound',
            field=models.BooleanField(default=True, help_text='Allow video clips to include an audio track. Automatically disabled when allow_videos is off.'),
        ),
        migrations.AlterField(
            model_name='board',
            name='allow_videos',
            field=models.BooleanField(default=True, help_text='Allow users to attach short video clips (MP4/WebM) to threads and posts on this board. Automatically disabled when allow_images is off.'),
        ),
    ]
