# Generated by Django 5.2.15 on 2026-06-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_board_video_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='remote_actor_url',
            field=models.URLField(blank=True, help_text='AP Actor URL of the remote author. Null for local threads.', null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='remote_ap_id',
            field=models.URLField(blank=True, help_text='ActivityPub Note ID on the origin server. Null for local threads.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='remote_actor_url',
            field=models.URLField(blank=True, help_text='AP Actor URL for remote stub users. Null for local accounts.', null=True, unique=True),
        ),
    ]
