# Generated by Django 5.2.15 on 2026-06-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_thread_is_remote_thread_remote_actor_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='allow_federation',
            field=models.BooleanField(default=True, help_text='Include this board in ActivityPub federation. Disable to keep the board local-only — it will not appear in the instance board list and threads will not be delivered to remote instances. Admin-only setting.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='federation_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for ActivityPub federation. Disable to pause all inbound and outbound federation without removing instance mappings or board configurations. Individual boards can also be excluded via their allow_federation flag.'),
        ),
    ]
