# Generated by Django 5.2.15 on 2026-06-24 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_post_federation_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username_last_changed_at',
            new_name='display_name_last_changed_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_username_change_audit',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='username_change_cooldown_days',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='display_name_change_cooldown_days',
            field=models.PositiveIntegerField(default=14, help_text='Minimum days a user must wait between display name changes. 0 = no cooldown. Enforced via User.display_name_last_changed_at, which is tracked regardless of the audit-log toggle above.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_display_name_change_audit',
            field=models.BooleanField(default=True, help_text='Log every display name change (old name, new name, when) to DisplayNameChangeLog. Independent of the cooldown below — turning this off stops new log entries but does not affect whether changes are still rate-limited.'),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='DisplayNameChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_display_name', models.CharField(max_length=150)),
                ('new_display_name', models.CharField(max_length=150)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_name_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.DeleteModel(
            name='UsernameChangeLog',
        ),
    ]
