# Generated by Django 5.2.15 on 2026-06-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_display_name_and_rename_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_avatars',
            field=models.BooleanField(default=False, help_text='Allow users to upload profile avatars. Disabled by default — enable only if you are comfortable hosting user-uploaded images.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_avatar_size_kb',
            field=models.PositiveIntegerField(default=512, help_text='Maximum avatar upload size in kilobytes. 512KB is plenty for a profile picture.'),
        ),
    ]
