# Generated by Django 5.2.15 on 2026-06-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_create_prune_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_communities',
            field=models.BooleanField(default=True, help_text='Enable the communities feature. When off, community creation is disabled and the communities nav link is hidden. Existing communities are unaffected.'),
        ),
    ]
