# Generated by Django 5.2.15 on 2026-06-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_enable_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_markdown',
            field=models.BooleanField(default=True, help_text='Allow markdown formatting in posts and replies. When off, body text is rendered as plain text.'),
        ),
    ]
