# Generated by Django 5.2.15 on 2026-06-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_allow_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_post_editing',
            field=models.BooleanField(default=False, help_text='Allow users to edit their own posts after submission.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='post_edit_window_seconds',
            field=models.PositiveIntegerField(default=90, help_text='How long (in seconds) a user has to edit a post after submission. 0 = unlimited.'),
        ),
    ]
