# Generated by Django 5.2.15 on 2026-06-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_post_editing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-safe identifier, e.g. "rules", "faq", "about". Accessible at /pages/<slug>/.', unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, help_text='Markdown content. Leave blank to show a placeholder.')),
                ('published', models.BooleanField(default=True, help_text='Unpublished pages are not accessible to the public.')),
                ('show_in_footer', models.BooleanField(default=True, help_text='Show a link to this page in the site footer.')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the footer. 0 = unordered.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_pages',
            field=models.BooleanField(default=False, help_text='Create, edit, and publish site pages (Rules, FAQ, etc.).'),
        ),
    ]
