# Generated by Django 5.2.15 on 2026-06-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_update_sitepage_placeholder_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='max_boards',
        ),
    ]
