# Generated by Django 5.2.15 on 2026-06-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_user_age_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='relay_hop_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='relay_seen_instances',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_relay_hops',
            field=models.PositiveIntegerField(default=5, help_text="Maximum number of instance-to-instance hops a relayed activity may travel before this instance stops forwarding it further. Caps relay chain length even if the seen-instances loop guard is somehow bypassed (e.g. a non-FaceChan AP server in the chain that doesn't preserve the seen-instances field). Only relevant when relay_federation_enabled is on."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='relay_federation_enabled',
            field=models.BooleanField(default=False, help_text="When on, threads/replies received from one federated instance are re-forwarded to this instance's own followers, preserving the original author and Note id — building a relay chain (1→2→3) rather than requiring every instance to follow every other instance directly. Off by default: the safer, simpler mode where each instance only delivers what it originates itself. Has no effect if federation_enabled is off."),
        ),
        migrations.AddField(
            model_name='thread',
            name='relay_hop_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of instance-to-instance hops this activity has travelled. 0 for content that originated here or arrived direct from its origin. Incremented by 1 each time an instance relays it onward. Relaying stops once SiteSettings.max_relay_hops is reached.'),
        ),
        migrations.AddField(
            model_name='thread',
            name='relay_seen_instances',
            field=models.JSONField(blank=True, default=list, help_text='List of instance domains this activity has already passed through (origin first, most recent relay last). Used to prevent relay loops — an instance must never relay an activity back to a domain already in this list. Empty for content that originated here.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='remote_actor_url',
            field=models.URLField(blank=True, help_text="AP URL of the remote actor who authored this post. Null for local posts. Preserved as-is through relay hops — always the ORIGINAL author, never a relaying instance's stub user.", null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='remote_actor_url',
            field=models.URLField(blank=True, help_text="AP Actor URL of the remote author. Null for local threads. Preserved as-is through relay hops — always the ORIGINAL author, never a relaying instance's stub user.", null=True),
        ),
    ]
