# Generated by Django 5.2.15 on 2026-07-02 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_post_relay_hop_count_post_relay_seen_instances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Internal board not shown in the public board list or board-scoped moderation assignment (e.g. the hidden board that holds private message threads). Not intended to be created or edited by operators.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_private_messages',
            field=models.BooleanField(default=True, help_text='Allow members to start private-message conversations with each other. When off, no new conversations can be started (existing ones remain in the database but become inaccessible).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='private_message_staff_access_enabled',
            field=models.BooleanField(default=False, help_text='OFF by default. When enabled, admin-tier staff can read private-message threads via the report/mod-queue path even without a report being filed. Intended for a narrow purpose — e.g. responding to a law-enforcement request — not routine moderation. Every toggle to True is stamped below for the audit trail; fill in a reason before saving.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='private_message_staff_access_enabled_at',
            field=models.DateTimeField(blank=True, help_text='When private_message_staff_access_enabled was last switched to True. Read-only audit field.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='private_message_staff_access_enabled_by',
            field=models.ForeignKey(blank=True, help_text='Admin who last switched private_message_staff_access_enabled to True. Read-only audit field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='private_message_staff_access_reason',
            field=models.CharField(blank=True, help_text='Required justification for turning staff access on (e.g. case/request reference). Kept as a permanent record even after the flag is turned back off.', max_length=300),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_private_message',
            field=models.BooleanField(default=False, help_text='True for a private-message conversation thread. Excluded from all public listings, feeds, and federation regardless of other settings.'),
        ),
        migrations.AddField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Invited members of a private-message thread. Only meaningful when is_private_message is True.', related_name='private_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
