# Generated by Django 5.2.15 on 2026-07-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_board_is_system_sitesettings_enable_private_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='private_message_retention_days',
            field=models.PositiveIntegerField(default=0, help_text='Automatically delete private-message conversations that have had no new messages for this many days (mirrors community_prune_days — same no-exceptions daily prune, see core.tasks.prune_inactive_conversations). 0 = disabled, conversations kept indefinitely.'),
        ),
    ]
