# Generated by Django 6.0.7 on 2026-07-09 13:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_create_prune_conversations_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='markdown_enabled',
            field=models.BooleanField(default=core.models._default_markdown_enabled, help_text='If enabled, posts on this board render full markdown (headers, lists, emphasis, code blocks, etc). If disabled, only greentext (">text") and line breaks are applied. New boards default to the site-wide "allow_markdown" setting at creation time; this can then be overridden per board. Admin-only setting.'),
        ),
    ]
