# Generated by Django 6.0.7 on 2026-07-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_board_markdown_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
