# Generated by Django 5.2.15 on 2026-06-22 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0028_board_video_sound'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('actor_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('Group', 'Group'), ('Person', 'Person')], max_length=10)),
                ('private_key_pem', models.TextField(editable=False)),
                ('public_key_pem', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_actor', to='core.board')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_actor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteActor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ap_id', models.URLField(unique=True)),
                ('actor_type', models.CharField(max_length=20)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('inbox_url', models.URLField()),
                ('public_key_pem', models.TextField()),
                ('key_id', models.URLField()),
                ('raw_json', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='federation.remoteinstance')),
            ],
        ),
        migrations.CreateModel(
            name='FederationActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('activity_type', models.CharField(max_length=50)),
                ('activity_id', models.URLField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='queued', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='federation.actor')),
                ('remote_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='federation.remoteinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follow_activity_id', models.URLField()),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='federation.actor')),
                ('remote_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='federation.remoteactor')),
            ],
            options={
                'unique_together': {('local_actor', 'remote_actor')},
            },
        ),
    ]
