# Generated by Django 5.2.15 on 2026-06-22 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_thread_is_remote_thread_remote_actor_url_and_more'),
        ('federation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteBoardMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_slug', models.CharField(help_text='Board slug on the remote instance e.g. "Pols" or "TechyStuff"', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_mappings', to='federation.remoteinstance')),
                ('local_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_mappings', to='core.board')),
            ],
            options={
                'ordering': ['instance__domain', 'remote_slug'],
                'unique_together': {('instance', 'remote_slug')},
            },
        ),
    ]
