# Generated by Django 5.2.15 on 2026-06-22 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0002_remoteboardmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_slug', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('nsfw', models.BooleanField(default=False)),
                ('actor_url', models.URLField(blank=True)),
                ('inbox_url', models.URLField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_boards', to='federation.remoteinstance')),
            ],
            options={
                'ordering': ['instance__domain', 'remote_slug'],
                'unique_together': {('instance', 'remote_slug')},
            },
        ),
    ]
