# Generated by Django 5.2.15 on 2026-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0003_remoteboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteboardmapping',
            name='follow_accepted',
            field=models.BooleanField(default=None, help_text='None=not sent, False=pending Accept, True=accepted', null=True),
        ),
    ]
