# Generated by Django 5.2.15 on 2026-06-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0004_add_follow_accepted_to_remoteboardmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationactivity',
            name='is_relay',
            field=models.BooleanField(default=False, help_text='True if this is a relay delivery (re-forwarding content that originated on another instance) rather than an origin delivery (content that originated on this instance). Only meaningful for outbound Create activities — see federation/tasks.py relay_create_thread vs deliver_create_thread.'),
        ),
    ]
